# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 40, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 100, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 100, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(370, 100, 47, 13))
        self.label_6.setObjectName("label_6")
        self.mI1_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.mI1_sb.setGeometry(QtCore.QRect(50, 60, 61, 22))
        self.mI1_sb.setMaximum(1000)
        self.mI1_sb.setObjectName("mI1_sb")
        self.mI2_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.mI2_sb.setGeometry(QtCore.QRect(210, 60, 61, 22))
        self.mI2_sb.setMaximum(1000)
        self.mI2_sb.setObjectName("mI2_sb")
        self.mI3_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.mI3_sb.setGeometry(QtCore.QRect(370, 60, 61, 22))
        self.mI3_sb.setMaximum(1000)
        self.mI3_sb.setObjectName("mI3_sb")
        self.aI1_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.aI1_sb.setGeometry(QtCore.QRect(50, 120, 61, 22))
        self.aI1_sb.setMaximum(1000)
        self.aI1_sb.setObjectName("aI1_sb")
        self.aI2_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.aI2_sb.setGeometry(QtCore.QRect(210, 120, 61, 22))
        self.aI2_sb.setMaximum(1000)
        self.aI2_sb.setObjectName("aI2_sb")
        self.aI3_sb = QtWidgets.QSpinBox(self.centralwidget)
        self.aI3_sb.setGeometry(QtCore.QRect(370, 120, 61, 22))
        self.aI3_sb.setMaximum(1000)
        self.aI3_sb.setObjectName("aI3_sb")
        self.draw_area = QtWidgets.QLabel(self.centralwidget)
        self.draw_area.setGeometry(QtCore.QRect(150, 240, 421, 251))
        self.draw_area.setText("")
        self.draw_area.setObjectName("draw_area")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "mod(I1)"))
        self.label_2.setText(_translate("MainWindow", "mod(I2)"))
        self.label_3.setText(_translate("MainWindow", "mod(I3)"))
        self.label_4.setText(_translate("MainWindow", "arg(I1)"))
        self.label_5.setText(_translate("MainWindow", "arg(I2)"))
        self.label_6.setText(_translate("MainWindow", "arg(I3)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
